[application]
name = "Isle"
default_platform = "desktop"

[bundle]
identifier = "com.lsle.demo"
publisher = "Lsle"
icon = ["icons/icon.ico", "icons/icon.png", "assets/icon.ico", "assets/logo.png"]
# 默认情况下 dx bundle 会寻找 icons 目录，同时也保留 assets 目录的配置


# 这里的配置有助于确保打包工具能找到必要的资源
